name: Tests

on:
  push:

jobs:
  test-hashlink:
    strategy:
      matrix:
        haxe-version: [4.2.5, 4.3.7]
    # AL init fails on both windows and ubuntu
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: krdlab/setup-haxe@v2
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - name: Set up Haxelib dependencies
      run: |
        haxelib update haxelib --global
        haxelib fixrepo
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install actuate --quiet
        haxelib install utest --quiet
        haxelib dev feathersui ${{ github.workspace }}
    - name: Run Tests
      working-directory: test
      run: haxelib run openfl test hl
